### PR TITLE
control reagent input presence explicitly

### LINKED ISSUE #204: Let UIx users tweak what value `should-use-reagent-input?` returns
**Describe the bug**
`should-use-reagent-input?`'s implementation assumes that the presence of Reagent alone should be enough to decide if a hack should be applied at the creation of an `input` element.

With the new WIP version of Reagent, this is no longer the case. In the new version, the render batching is disabled and applying the hack to the input elements prevents their value to be updated at all.

**Include minimal repro**
1. Use the branch `reagent-next` of Reagent.
2. Use UIx v1.3.1.
3. Use React 18.3.1 (probably the same problem happens with React 19.0.0)
4. Create a controlled input element on a page. Its value won't change when we type.
```clojure
(defui input-using-react-state []
  (let [[value set-value] (uix/use-state "try changing me")
        on-change (uix/use-callback (fn [^js event]
                                      (set-value (-> event .-target .-value)))
                                    [])]
    ($ :div
       ($ :input {:value value
                  :onChange on-change}))))
```

Please note that it also happens when using `uix.dom/create-root` and `uix.dom/render-root`.

**Expected behavior**
There should be a way to let the UIx user override what `should-use-reagent-input?` returns.

**Additional context**
We are trying to migrate an app which contains both Reagent and UIx components to React 19 and are currently using the WIP branch of Reagent.

### PR DESCRIPTION
**Pull request by roman01la**
fixes #204 

@Deraen @green-coder looking good?

### CODE REVIEW

**Comment by accounts-pitch-io** [comment]
master:
react x 10235 ops/s, elapsed 977ms
uix x 7758 ops/s, elapsed 1289ms
helix x 7728 ops/s, elapsed 1294ms
reagent x 5297 ops/s, elapsed 1888ms


PR:
react x 11099 ops/s, elapsed 901ms
uix x 8569 ops/s, elapsed 1167ms
helix x 8292 ops/s, elapsed 1206ms
reagent x 6057 ops/s, elapsed 1651ms

File: core/test/uix/core_test.cljs [hunk 1]
```diff
@@ -440,5 +440,18 @@
       (is (= identity (.. el -props -onClick)))
       (is (= "red" (.. el -props -style -color))))))
 
+(deftest test-204
+  (testing "should use Reagent's input when Reagent's context is *non-reactive*"
```
Comment (Deraen) [inline core/test/uix/core_test.cljs:444]: is "not non-reactive" / is reactive
